### ISSUE TITLE
purpose of dom.js?

### ISSUE THREAD

**Issue by shamel67** [fent/chrome-options#4]
It looks like in your example, the dom.js is just a stub to replace native Chrome features. I searched for a while because chrome.runtime.getManifest() was returning an empty object. Once I removed dom.js, everything started working fine.

**Comment by fent** [comment]
There are various helper functions in dom.js that are not available in Chrome

https://github.com/fent/chrome-options/blob/master/dom.js

I'm not sure that removing would help since its functions are used by the main chrome-options.js file. Are you getting an error? Also not sure of which example are you referring to?

**Comment by shamel67** [comment]
Sorry - I meant chrome.js... my bad... chrome.js is only used for the demo and I started from it to build my options page. It took me a while to realize chrome.js was just a stub.
